
services:
  redis:
    image: redis:7-alpine
    container_name: job-redis
    ports:
      - "6379:6379"
    networks:
      - job-network
    restart: always

  job-master:
    build:
      context: .
      dockerfile: Dockerfile.jobmaster
    container_name: job-master
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://3.16.110.253:27017/stock-market
      - REDIS_URL=redis://redis:6379
      #- MAIN_API_URL=https://api.eberosg.me
      - MAIN_API_URL=http://host.docker.internal:3000
    ports:
      - "4000:4000"
    networks:
      - job-network
    restart: always
    volumes:
      - ./logs:/app/logs

  estimation-worker:
    build:
      context: .
      dockerfile: Dockerfile.estimation
    container_name: estimation-worker
    depends_on:
      - redis
      - job-master
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://3.16.110.253:27017/stock-market
      - REDIS_URL=redis://redis:6379
      #- MAIN_API_URL=https://api.eberosg.me
      - MAIN_API_URL=http://host.docker.internal:3000
      - AUTH0_URL=https://dev-qtg1vycp6zc4uv20.us.auth0.com/oauth/token
      - AUTH0_CLIENT_ID=ah9AII5mfWddiNDph6iUR48Yb7gdTcKc
      - AUTH0_SECRET=gFIQgJRDlJ5RI0_Vp1A8dY2aqRhVgL0_3whrRPw0mFJimBPCcC33ppIhUVfktJJn
    command: ["npm", "run", "worker"]
    networks:
      - job-network
    restart: always
    volumes:
      - ./logs:/app/logs

networks:
  job-network:
    driver: bridge